const menuData = [
    { category: "한식", name: "김치찌개", description: "얼큰하고 시원한 국물에 김치와 돼지고기가 어우러진 한국인의 소울푸드." },
    { category: "한식", name: "된장찌개", description: "구수한 된장과 다양한 채소, 두부가 들어간 한국 대표 찌개." },
    { category: "한식", name: "비빔밥", description: "따뜻한 밥 위에 나물, 고기, 고추장을 넣어 비벼 먹는 영양 만점 한 그릇." },
    { category: "한식", name: "불고기", description: "달콤 짭짤한 양념에 재운 소고기를 구워 먹는 남녀노소 인기 메뉴." },
    { category: "한식", name: "잡채", description: "다채로운 채소와 당면을 간장 양념에 볶아 만든 잔치 음식." },
    { category: "한식", name: "삼겹살", description: "고소한 돼지고기 삼겹살을 불판에 구워 쌈 싸 먹는 한국 대표 외식 메뉴." },
    { category: "한식", name: "순두부찌개", description: "부드러운 순두부와 해산물이 들어간 얼큰하고 뜨거운 찌개." },
    { category: "한식", name: "갈비탕", description: "푹 고아낸 소갈비 육수에 부드러운 갈빗대가 들어간 보양식." },
    { category: "한식", name: "제육볶음", description: "매콤달콤한 고추장 양념에 돼지고기를 볶아 만든 밥도둑." },
    { category: "한식", name: "닭갈비", description: "매콤한 양념에 닭고기, 채소, 떡 등을 넣어 볶아 먹는 철판 요리." },
    { category: "한식", name: "떡볶이", description: "매콤달콤한 고추장 양념에 쫀득한 떡과 어묵을 넣어 끓인 국민 간식." },
    { category: "한식", name: "감자탕", description: "돼지 등뼈와 감자, 얼갈이배추 등을 넣고 얼큰하게 끓인 탕." },
    { category: "한식", name: "뼈해장국", description: "푸짐한 돼지 등뼈와 우거지가 들어간 해장에도 좋은 얼큰한 국물 요리." },
    { category: "한식", name: "순대국밥", description: "든든한 순대와 돼지 부속을 넣고 끓인 구수하고 뜨거운 국밥." },
    { category: "한식", name: "라면", description: "간편하게 즐기는 얼큰한 국물의 면 요리, 다양한 종류가 있어요." },
    { category: "한식", name: "김밥", description: "밥과 다양한 재료를 김으로 말아 만든 한국인의 소풍 메뉴." },
    { category: "한식", name: "닭볶음탕", description: "매콤한 양념에 닭고기와 감자, 당근 등을 넣고 끓인 요리." },
    { category: "한식", name: "칼국수", description: "쫄깃한 면발과 시원한 육수가 일품인 한국식 면 요리." },
    { category: "한식", name: "부대찌개", description: "햄, 소시지, 라면 등 다양한 재료를 넣고 얼큰하게 끓인 퓨전 찌개." },
    { category: "한식", name: "회덮밥", description: "신선한 회와 채소를 밥 위에 얹고 초고추장에 비벼 먹는 상큼한 덮밥." },
    { category: "한식", name: "콩나물 국밥", description: "시원하고 개운한 콩나물 육수에 밥을 말아 먹는 해장 국밥." },

    { category: "중식", name: "짜장면", description: "춘장에 돼지고기와 채소를 볶아 면에 비벼 먹는 한국식 중화요리." },
    { category: "중식", name: "짬뽕", description: "얼큰하고 시원한 해물 육수에 면을 넣어 끓인 한국식 중화요리." },
    { category: "중식", name: "탕수육", description: "바삭하게 튀긴 돼지고기에 달콤새콤한 소스를 부어 먹는 요리." },
    { category: "중식", name: "마파두부", description: "매콤한 양념에 두부와 다진 고기를 볶아 만든 중국 사천 요리." },
    { category: "중식", name: "양장피", description: "겨자 소스에 해산물과 채소를 버무려 먹는 상큼한 중국 요리." },
    { category: "중식", name: "깐풍기", description: "바삭하게 튀긴 닭고기에 매콤달콤한 소스를 버무린 중국 요리." },
    { category: "중식", name: "고추잡채", description: "얇게 썬 피망과 고기를 볶아 꽃빵에 싸 먹는 중국 요리." },
    { category: "중식", name: "동파육", description: "부드럽게 삶은 돼지고기 삼겹살에 간장 소스를 곁들인 중국 항주 요리." },
    { category: "중식", name: "울면", description: "걸쭉한 국물에 해산물과 면을 넣어 끓인 따뜻한 중국 면 요리." },
    { category: "중식", name: "기스면", description: "맑은 닭고기 육수에 가는 면을 넣어 끓인 담백한 중국 면 요리." },
    { category: "중식", name: "볶음밥", description: "고슬고슬한 밥에 다양한 재료를 넣고 볶아 만든 식사 메뉴." },
    { category: "중식", name: "꿔바로우", description: "찹쌀 튀김옷을 입힌 탕수육으로, 쫄깃한 식감이 특징." },
    { category: "중식", name: "유린기", description: "바삭하게 튀긴 닭고기에 새콤달콤한 간장 소스를 뿌려 먹는 요리." },
    { category: "중식", name: "깐쇼새우", description: "매콤달콤한 칠리 소스에 통통한 새우를 볶아낸 요리." },
    { category: "중식", name: "XO볶음밥", description: "XO 소스로 맛을 낸 고급스러운 해산물 볶음밥." },

    { category: "일식", name: "초밥", description: "신선한 해산물과 밥을 쥐어 만든 일본 대표 요리." },
    { category: "일식", name: "라멘", description: "깊고 진한 육수에 면과 다양한 고명을 얹은 일본식 국수." },
    { category: "일식", name: "돈까스", description: "바삭하게 튀긴 돼지고기 커틀릿에 소스를 뿌려 먹는 요리." },
    { category: "일식", name: "우동", description: "쫄깃한 면발과 따뜻한 국물이 어우러진 일본식 면 요리." },
    { category: "일식", name: "소바", description: "메밀 면을 차가운 쯔유에 찍어 먹거나 따뜻한 국물에 넣어 먹는 요리." },
    { category: "일식", name: "오니기리", description: "다양한 속재료를 넣고 모양을 낸 일본식 주먹밥." },
    { category: "일식", name: "텐동", description: "갓 튀긴 튀김을 밥 위에 얹고 특제 소스를 뿌려 먹는 일본식 덮밥." },
    { category: "일식", name: "가츠동", description: "돈까스를 계란과 함께 밥 위에 얹어 먹는 일본식 덮밥." },
    { category: "일식", name: "스키야키", description: "얇게 썬 고기와 채소를 달콤 짭짤한 육수에 끓여 먹는 일본식 전골." },
    { category: "일식", name: "오코노미야키", description: "밀가루 반죽에 해산물, 고기, 채소를 넣고 철판에 구워 만든 일본식 부침개." },
    { category: "일식", name: "규동", description: "얇게 썬 소고기를 달콤한 양념에 볶아 밥 위에 얹어 먹는 덮밥." },
    { category: "일식", name: "사케동", description: "신선한 연어회를 밥 위에 얹어 먹는 일본식 덮밥." },
    { category: "일식", name: "타코야키", description: "문어 조각을 넣은 밀가루 반죽을 구워 만든 일본 길거리 음식." },
    { category: "일식", name: "야키토리", description: "닭고기나 채소를 꼬치에 꿰어 구워 만든 일본식 꼬치구이." },
    { category: "일식", name: "카레라이스", description: "일본식 카레 소스를 밥 위에 얹어 먹는 식사 메뉴." },

    { category: "양식", name: "파스타", description: "다양한 소스와 면을 활용한 이탈리아 대표 요리." },
    { category: "양식", name: "피자", description: "얇은 도우에 토마토 소스, 치즈, 토핑을 얹어 구운 이탈리아 요리." },
    { category: "양식", name: "스테이크", description: "육즙 가득한 소고기를 구워 즐기는 고급 서양 요리." },
    { category: "양식", name: "리조또", description: "쌀을 육수에 졸여 만든 이탈리아식 쌀 요리." },
    { category: "양식", name: "햄버거", description: "빵 사이에 패티와 채소를 넣어 만든 대표적인 서양 패스트푸드." },
    { category: "양식", name: "시저 샐러드", description: "로메인 상추에 크루통, 파마산 치즈를 얹고 드레싱을 뿌린 샐러드." },
    { category: "양식", name: "감바스 알 아히요", description: "올리브 오일에 새우와 마늘을 끓여 만든 스페인 요리." },
    { category: "양식", name: "에그 베네딕트", description: "잉글리시 머핀 위에 햄, 수란, 홀랜다이즈 소스를 얹은 브런치 메뉴." },
    { category: "양식", name: "클램 차우더", description: "조개와 감자, 크림을 넣어 만든 걸쭉한 서양식 수프." },
    { category: "양식", name: "바베큐 립", description: "특제 소스를 발라 구운 부드러운 돼지갈비." },
    { category: "양식", name: "라자냐", description: "겹겹이 쌓은 파스타 면과 미트소스, 치즈로 만든 이탈리아 요리." },
    { category: "양식", name: "뇨끼", description: "감자로 만든 쫄깃한 이탈리아식 수제비." },
    { category: "양식", name: "샐러드 파스타", description: "신선한 채소와 파스타를 드레싱에 버무려 먹는 가벼운 메뉴." },
    { category: "양식", name: "치킨 로스트", description: "오븐에 통째로 구워낸 담백하고 부드러운 닭 요리." },
    { category: "양식", name: "퀘사디아", description: "또띠아에 치즈와 다양한 재료를 넣고 반으로 접어 구운 멕시코 요리." },

    { category: "아시안", name: "쌀국수", description: "따뜻하고 시원한 육수에 면과 고기가 들어간 베트남 대표 국수." },
    { category: "아시안", name: "팟타이", description: "새우, 땅콩, 숙주 등과 함께 볶아 만든 태국식 볶음 쌀국수." },
    { category: "아시안", name: "분짜", description: "차가운 면과 숯불 돼지고기, 채소를 느억맘 소스에 찍어 먹는 베트남 요리." },
    { category: "아시안", name: "나시고랭", description: "닭고기, 새우, 채소를 넣고 볶아 만든 인도네시아식 볶음밥." },
    { category: "아시안", name: "똠양꿍", description: "새우와 버섯, 고수 등을 넣고 끓인 시고 매운 태국 대표 수프." },
    { category: "아시안", name: "커리", description: "다양한 향신료와 재료를 넣어 만든 인도 및 아시아 지역의 걸쭉한 요리." },
    { category: "아시안", name: "사테", description: "꼬치에 꿰어 구운 고기에 땅콩 소스를 곁들인 동남아시아 요리." },
    { category: "아시안", name: "월남쌈", description: "신선한 채소와 고기를 라이스페이퍼에 싸서 소스에 찍어 먹는 베트남 요리." },
    { category: "아시안", name: "마라탕", description: "얼얼하고 매운 중국 사천 지방의 향신료를 넣어 끓인 탕." },
    { category: "아시안", name: "반미", description: "바게트 빵에 고기, 채소를 넣어 만든 베트남식 샌드위치." },
    { category: "아시안", name: "팟카파오무쌉", description: "다진 돼지고기와 바질을 넣고 볶아 밥과 함께 먹는 태국 요리." },
    { category: "아시안", name: "푸팟퐁커리", description: "껍질째 먹는 게와 커리 소스가 어우러진 태국 요리." },
    { category: "아시안", name: "카오팟", description: "태국식 볶음밥으로, 다양한 재료를 넣어 볶아 만든다." },
    { category: "아시안", name: "미고랭", description: "인도네시아식 볶음면으로, 달콤 짭짤한 맛이 특징." },
    { category: "아시안", name: "꿔띠아오", description: "태국식 쌀국수로, 맑은 육수와 부드러운 면발이 특징." }
];