const menuData = [
    { category: "한식", name: "김치찌개" },
    { category: "한식", name: "된장찌개" },
    { category: "한식", name: "비빔밥" },
    { category: "한식", name: "불고기" },
    { category: "한식", name: "잡채" },
    { category: "한식", name: "삼겹살" },
    { category: "한식", name: "순두부찌개" },
    { category: "한식", name: "갈비탕" },
    { category: "한식", name: "제육볶음" },
    { category: "한식", name: "닭갈비" },
    { category: "중식", name: "짜장면" },
    { category: "중식", name: "짬뽕" },
    { category: "중식", name: "탕수육" },
    { category: "중식", name: "마파두부" },
    { category: "중식", name: "양장피" },
    { category: "중식", name: "깐풍기" },
    { category: "중식", name: "고추잡채" },
    { category: "중식", name: "동파육" },
    { category: "중식", name: "울면" },
    { category: "중식", name: "기스면" },
    { category: "일식", name: "초밥" },
    { category: "일식", name: "라멘" },
    { category: "일식", name: "돈까스" },
    { category: "일식", name: "우동" },
    { category: "일식", name: "소바" },
    { category: "일식", name: "오니기리" },
    { category: "일식", name: "텐동" },
    { category: "일식", name: "가츠동" },
    { category: "일식", name: "스키야키" },
    { category: "일식", name: "오코노미야키" },
    { category: "양식", name: "파스타" },
    { category: "양식", name: "피자" },
    { category: "양식", name: "스테이크" },
    { category: "양식", name: "리조또" },
    { category: "양식", name: "햄버거" },
    { category: "양식", name: "시저 샐러드" },
    { category: "양식", name: "감바스 알 아히요" },
    { category: "양식", name: "에그 베네딕트" },
    { category: "양식", name: "클램 차우더" },
    { category: "양식", name: "바베큐 립" },
    { category: "아시안", name: "쌀국수" },
    { category: "아시안", name: "팟타이" },
    { category: "아시안", name: "분짜" },
    { category: "아시안", name: "나시고랭" },
    { category: "아시안", name: "똠양꿍" },
    { category: "아시안", name: "커리" },
    { category: "아시안", name: "사테" },
    { category: "아시안", name: "월남쌈" },
    { category: "아시안", name: "마라탕" },
    { category: "아시안", name: "반미" }
];
